version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands:
      - echo Running tests...
      - pytest
