version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install flask
  build:
    commands:
      - echo "Build phase - nothing to build for Flask app"
artifacts:
  files:
    - '**/*'
    - 'scripts/**'
