version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running lint...
      - flake8 app.py  # or pylint if preferred
artifacts:
  files:
    - '**/*'
